# Generated by Django 6.0 on 2025-12-27 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Название сайта ')),
                ('description', models.TextField(verbose_name='Описание ')),
                ('phone', models.CharField(max_length=100, verbose_name='Номер телефона ')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('locate', models.CharField(max_length=100, verbose_name='Адрес сайта ')),
                ('logo', models.ImageField(upload_to='logos/', verbose_name='Логотип сайта ')),
            ],
            options={
                'verbose_name': 'Настройка сайта ',
                'verbose_name_plural': 'Настройкии сайта ',
            },
        ),
    ]
